kind: Service
apiVersion: apps/v1
metadata:
  name: clusreripservice
  labels:
    kind: normalservice
spec:
  selector:
    name: saivinay
    dept: cse
    year: twenty
  ports:
  - name: webport
    protocol: TCP
    ports: 80
    targetPort: 80
