kind: Service
apiVersion: apps/v1
metadata:
  name: clusreripservice
  labels:
    kind: normalservice
spec:
  selector:
    name: cluster
  ports:
  - name: webport
    protocol: TCP
    ports: 80
    targetPort: 80
    
---
apiVersion: v1
kind: Pod
metadata:
  name: labelpod
  namespace: roboshop
  labels:
    name: cluster
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap 


