# kind: Pod
# apiVersion: v1
# metadata:
#   name: firstpod
#   namespace: roboshop
#   labels:
#     name: web
#     kind: application
# spec:
#   containers:
#   - image: nginx
#     name: weapp
#     conrainerPort: 80
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap
  namespace: roboshop
data:
  MY_SQL: mysql
  USER: user
---
apiVersion: v1
metadata:
  name: labelpod
  namespace: roboshop
  labels:
    name: saivinay
    dept: cse
    year: twenty
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap 
